package gw.rules.all.policyperiod

/**
 * Created with IntelliJ IDEA.
 * User: parumugam
 * Date: 2/7/17
 * Time: 11:07 AM
 * To change this template use File | Settings | File Templates.
 */
class DocElevationFlood  extends DocumentRequestRuleExecution{
  //TODO TLV keeping this to retain the related activity pattern.  Will likely be generated by a workflow.
//  var activityPattern = ActivityPattern.finder.getActivityPatternByCode("flood_elevation_follow_up")
//  var activity = activityPattern.createJobActivity(target.Bundle, target.Job, null, null, null, null, null, null, null)
//  ActivityUtil.assignActivityToQueue(ActivityUtil.ACTIVITY_QUEUE.CSR_FOLLOW_UP.QueueName, ActivityUtil.ACTIVITY_QUEUE.CSR_FOLLOW_UP.QueueName, activity)

  override function shouldGenerateDocumentRequest(period: PolicyPeriod): boolean {
    return period.HomeownersLine_HOEExists
       and period.Status == typekey.PolicyPeriodStatus.TC_QUOTED
       and period.HomeownersLine_HOE?.Dwelling.AbveBlwBaseFldElvtn_Ext != null
       and typekey.AbveBlwBaseFldElvtn_Ext.TF_DOCLISTFILTER.TypeKeys.contains(period.HomeownersLine_HOE?.Dwelling.AbveBlwBaseFldElvtn_Ext)
  }

  override property get DocumentType(): DocumentRequestType_Ext {
    return TC_FloodElevationCertificate
  }
}

