package una.rating.ho.common

/**
 * User: bduraiswamy
 * Date: 6/16/16
 * Time: 11:47 AM
 * final class with the HO Rate Routine Names.
 */
public final class HORateRoutineNames {

  //base premium routines
  public static final var BASE_PREMIUM_RATE_ROUTINE : String = "UNAHOBasePremiumRateRoutine"
  public static final var HO_REPLACEMENT_COST_DWELLING_RATE_ROUTINE : String = "UNAHOReplacementCostRateRoutine"
  public static final var HO_REPLACEMENT_COST_PERSONAL_PROPERTY_RATE_ROUTINE : String = "UNAHOReplacementCostPersonalPropertyRateRoutine"
  public static final var HOA_PLUS_COVERAGE_RATE_ROUTINE : String = "UNAHOAPlusCoverageRateRoutine"
  //public static final var DP_BASE_PREMIUM_RATE_ROUTINE : String = "UNAHODPBasePremiumRateRoutine"

  //base premium routines for group 2 states
  public static final var BASE_PREMIUM_SC_RATE_ROUTINE : String = "UNAHOBasePremiumRateRoutine"

  public static final var MEDICAL_PAYMENTS_ROUTINE_NAME : String = "UNAHOMedicalPaymentsRateRoutine"
  public static final var PERSONAL_LIABILITY_ROUTINE_NAME : String = "UNAHOPersonalLiabilityRateRoutine"
  public static final var RESIDENTIAL_GLASS_COV_ROUTINE_NAME : String = "UNAHOResidentialGlassCovRateRoutine"
  public static final var LOSS_ASSESSMENT_COVERAGE_RATE_ROUTINE : String = "UNAHOLossAssessmentCovRateRoutine"
  public static final var MOLD_REMEDIATION_COV_ROUTINE_NAME : String = "UNAHOMoldRemediationCovRateRoutine"
  public static final var UNIT_OWNERS_OUTBUILDINGS_AND_OTHER_STRUCTURES_COV_ROUTINE_NAME : String = "UNAHOUnitOwnersOutbuildingsAndOtherStructuresCovRateRoutine"
  public static final var ADDITIONAL_RESIDENCE_RENTED_TO_OTHERS_COVERAGE_ROUTINE_NAME : String = "UNAHOAdditionalResidenceRentedToOthersRateRoutine"
  public static final var SCHEDULED_PERSONAL_PROPERTY_COV_ROUTINE_NAME : String = "UNAHOScheduledPersonalPropertyCovRateRoutine"

  public static final var PERSONAL_INJURY_COVERAGE_ROUTINE_NAME : String = "UNAHOPersonalInjuryCoverageRateRoutine"
  public static final var EQUIPMENT_BREAKDOWN_COV_ROUTINE_NAME : String = "UNAHOEquipmentBreakdownCovRateRoutine"
  public static final var ACV_LOSS_SETTLEMENT_ON_ROOF_SURFACING_ROUTINE_NAME : String = "UNAHOACVLossSettlementOnRoofSurfacingRateRoutine"
  public static final var OTHER_STRUCTURES_INCREASED_OR_DECREASED_LIMITS_COV_ROUTINE_NAME : String = "UNAHOOtherStructuresIncreasedOrDecreasedLimitsCovRateRoutine"
  public static final var ANIMAL_LIABILITY_COV_ROUTINE_NAME : String = "UNAHOAnimalLiabilityCovRateRoutine"
  public static final var IDENTITY_THEFT_EXPENSE_COV_ROUTINE_NAME : String = "UNAHOIdentityTheftExpenseCovRateRoutine"
  public static final var SPECIFIED_ADDITIONAL_AMOUNT_COV_ROUTINE_NAME : String = "UNAHOSpecifiedAdditionalAmountCovRateRoutine"
  public static final var PERSONAL_PROPERTY_INCREASED_LIMIT_COV_ROUTINE_NAME : String = "UNAHOPersonalPropertyIncreasedLimitRateRoutine"
  public static final var UNIT_OWNERS_RENTED_TO_OTHERS_COV_ROUTINE_NAME : String = "UNAHOUnitOwnersRentedToOthersCovRateRoutine"
  public static final var SEASONAL_OR_SECONDARY_RESIDENCE_SURCHARGE_RATE_ROUTINE : String = "UNAHOSeasonalOrSecondaryResidenceSurchargeRateRoutine"
  public static final var AGE_OF_HOME_DISCOUNT_RATE_ROUTINE : String = "UNAHOAgeOfHomeDiscountRateRoutine"
  public static final var BURGLAR_PROTECTIVE_DEVICES_CREDIT_RATE_ROUTINE : String = "UNAHOBurglarProtectiveDeviceCreditRateRoutine"
  public static final var FIRE_PROTECTIVE_DEVICES_CREDIT_RATE_ROUTINE : String = "UNAHOFireProtectiveDevicesCreditRateRoutine"
  public static final var POLICY_FEE_RATE_ROUTINE : String = "UNAHOPolicyFeeRateRoutine"
  public static final var MINIMUM_PREMIUM_ADJUSTMENT_RATE_ROUTINE : String = "UNAHOMinimumPremiumAdjustmentRateRoutine"
  public static final var ADDITIONAL_INSURED_RATE_ROUTINE : String = "UNAHOAdditionalInsuredRateRoutine"
  public static final var INCREASED_LIMITS_JEWELRY_WATCHES_FURS : String = "UNAHOIncreasedLimitsJewelryWatchesFursRateRoutine"
  public static final var EXECUTIVE_COVERAGE_RATE_ROUTINE : String = "UNAHOExecutiveCoverageRateRoutine"
  public static final var SUPERIOR_CONSTRUCTION_DISCOUNT_ROUTINE : String = "UNAHOSuperiorConstructionDiscount"
  public static final var HAIL_RESISTANT_ROOF_CREDIT_RATE_ROUTINE : String = "UNAHOHailResistantRoofCreditRateRoutine"
  public static final var HIGHER_ALL_PERIL_DEDUCTIBLE_RATE_ROUTINE : String = "UNAHOHigherAllPerilDeductible"
  public static final var AFFINITY_DISCOUNT_RATE_ROUTINE : String = "UNAHOAffinityDiscountRateRoutine"
  public static final var AGE_OF_HOME_PREMIUM_MODIFIER_RATE_ROUTINE : String = "UNAHOAgeOfHomePremiumModifierRateRoutine"
  public static final var PREFERRED_BUILDER_CREDIT_RATE_ROUTINE : String = "UNAHOPreferredBuilderCreditRateRoutine"
  public static final var MAXIMUM_DISCOUNT_ADJUSTMENT_RATE_ROUTINE : String = "UNAHOMaximumDiscountAdjustmentRateRoutine"
  public static final var MULTI_LINE_DISCOUNT_RATE_ROUTINE : String = "UNAHOMultiLineDiscountRateRoutine"
  public static final var WATERCRAFT_LIABILITY_COVERAGE_RATE_ROUTINE : String = "UNAHOWatercraftLiabilityCoverageRateRoutine"
  public static final var FIGA_SURCHARGE_RATE_ROUTINE : String = "UNAHOFIGASurchargeRateRoutine"
  public static final var EMPA_SURCHARGE_RATE_ROUTINE : String = "UNAHOEMPASurchargeRateRoutine"
  public static final var OUTBOARD_MOTORS_AND_WATERCRAFT_COV_GROUP2_ROUTINE_NAME : String = "UNAHOOutboardMotorsAndWatercraftCovGroup2RateRoutine"

  //group1 routines
  //TODO : Need to update the routine names for group1 states
  public static final var REFRIGERATED_PERSONAL_PROPERTY_COV_ROUTINE_NAME : String = "UNAHORefrigeratedPersonalPropertyCovRateRoutine"
  public static final var SPECIAL_COMPUTER_COV_ROUTINE_NAME : String = "UNAHOSpecialComputerCovRateRoutine"
  public static final var WATER_BACKUP_SUMP_OVERFLOW_COV_ROUTINE_NAME : String = "UNAHOWaterBackupSumpOverflowCovRateRoutine"
  public static final var OUTBOARD_MOTORS_AND_WATERCRAFT_COV_GROUP1_ROUTINE_NAME : String = "UNAHOOutboardMotorsAndWatercraftCovGroup1RateRoutine"
  public static final var LIMITED_FUNGI_WET_OR_DRY_ROT_OR_BACTERIA_SECTIONI_GROUP1_COV_ROUTINE_NAME : String = "UNAHOLimitedFungiWetOrDryRotOrBacteriaSectionIGroup1RateRoutine"
  public static final var ADDITIONAL_RESIDENCE_RENTED_TO_OTHERS_COVERAGE_GROUP1_ROUTINE_NAME : String = "UNAHOAddResidenceRentedToOthersGroup1RateRoutine"
  public static final var LIMITED_FUNGI_WET_OR_DRY_ROT_OR_BACTERIA_SECTIONII_GROUP1_COV_ROUTINE_NAME : String = "UNAHOLimitedFungiWetOrDryRotOrBacteriaSectionIIGroup1RateRoutine"
  public static final var SPECIAL_PERSONAL_PROPERTY_COVERAGE_ROUTINE_NAME : String = "UNASpecialPersonalPropertyGroup1RateRoutine"
  public static final var SPECIAL_LIMITS_PERSONAL_PROPERTY_COV_ROUTINE_NAME : String = "UNAHOSpecialLimitsPersonalPropertyCovRateRoutine"
  public static final var DIFFERENCE_IN_CONDITIONS_RATE_ROUTINE : String = "UNAHODifferenceInConditionsRateRoutine"
  public static final var CONCRETE_TILE_ROOF_DISCOUNT_RATE_ROUTINE : String = "UNAHOConcreteTileRoofDiscountRateRoutine"
  public static final var GATED_COMMUNITY_DISCOUNT_RATE_ROUTINE : String = "UNAHOGatedCommunityDiscountRateRoutine"
  public static final var WC_PRIVATE_RESIDENCE_EMPLOYEES_CA_RATE_ROUTINE : String = "UNAHOWCPrivateResidenceEmployeesCARateRoutine"
  public static final var PRIVATE_FIRE_COMPANY_DISCOUNT_AZ_RATE_ROUTINE : String = "UNAHOPrivateFireCompanyDiscountAZRateRoutine"
  public static final var VACANT_DWELLINGS_RATE_ROUTINE : String = "UNAHOVacantDwellingsRateRoutine"
  public static final var BUILDING_CODE_EFFECTIVENESS_GRADING_CREDIT_RATE_ROUTINE : String = "UNAHOBuildingCodeEffectivenessGradingCreditRateRoutine"
  public static final var ADDITIONAL_RESIDENCES_OCCUPIED_BY_INSURED_RATE_ROUTINE : String ="UNAHOAdditionalResidenceOccupiedByInsuredRateRoutine"
  public static final var PERMITTED_INCIDENTAL_OCCUPANCIES_RATE_ROUTINE : String = "UNAHOPermittedIncidentalOccupanciesRateRoutine"
  public static final var BUILDING_ADDITIONS_AND_ALTERATIONS_INCREASED_LIMITS_RATE_ROUTINE : String = "UNAHOBuildingAdditionsAndAlterationsIncreasedLimitsRateRoutine"
  public static final var FLOOD_COVERAGE_RATE_ROUTINE : String = "UNAHOFloodCoverageRateRoutine"
  public static final var WINDSTORM_MITIGATION_CREDIT_RATE_ROUTINE : String = "UNAHOWindstormMitigationCreditRateRoutine"

  // group3 states
  public static final var WIND_BASE_PREMIUM_RATE_ROUTINE : String = "UNAHOWindBasePremiumRateRoutine"
  public static final var BUSINESS_PROPERTY_INCREASED_LIMITS_RATE_ROUTINE : String = "UNAHOBusinessPropertyIncreasedLimitsRateRoutine"
  public static final var PERSONAL_PROPERTY_EXCLUSION_RATE_ROUTINE : String = "UNAHOPersonalPropertyExclusionRateRoutine"
  public static final var GOLF_CART_PHYSICAL_DAMAGE_AND_LIABILITY_COVERAGE_RATE_ROUTINE : String = "UNAHOGolfCartPhysicalDamageAndLiabilityCovRateRoutine"
  public static final var INCREASED_SECTION_II_LIMITS_ROUTINE_NAME : String = "UNAHOIncreasedSectionIILimitsRateRoutine"
  public static final var SINKHOLE_LOSS_COVERAGE_RATE_ROUTINE : String = "UNAHOSinkholeLossCoverageRateRoutine"
  public static final var ORDINANCE_OR_LAW_COV_ROUTINE_NAME : String = "UNAHOOrdinanceOrLawCovRateRoutine"
  public static final var LIMITED_SCREENED_ENCLOSURE_AND_CARPORT_COV_ROUTINE_NAME : String = "UNAHOLimitedScreenedEnclosureAndCarportCovRateRoutine"
  public static final var LIMITED_FUNGI_WET_OR_DRY_ROT_OR_BACTERIA_SECTIONI_COV_ROUTINE_NAME : String = "UNAHOLimitedFungiWetOrDryRotOrBacteriaSectionIRateRoutine"
  public static final var LIMITED_FUNGI_WET_OR_DRY_ROT_OR_BACTERIA_SECTIONII_COV_ROUTINE_NAME : String = "UNAHOLimitedFungiWetOrDryRotOrBacteriaSectionIIRateRoutine"
  public static final var MATURE_HOME_OWNER_DISCOUNT_RATE_ROUTINE : String = "UNAHOMatureHomeOwnerDiscountRateRoutine"
  public static final var BUILDING_CODE_NON_PARTICIPATING_RISKS_SURCHARGE_RATE_ROUTINE : String = "UNAHOBuildingCodeNonParticipatingRisksSurchargeRateRoutine"
  public static final var BUILDING_CODE_COMPLIANCE_GRADING_CREDIT_RATE_ROUTINE : String = "UNAHOBuildingCodeComplianceGradingCreditRateRoutine"
  public static final var WINDSTORM_RESISTIVE_FEATURES_OF_RESIDENTIAL_CONSTRUCTION_CREDIT_RATE_ROUTINE : String = "UNAHOWPDCCreditRateRoutine"
  public static final var OTHER_STRUCTURES_RENTED_TO_OTHERS_RATE_ROUTINE : String = "UNAHOOtherStructuresRentedToOthersRateRoutine"
  public static final var NCRB_PREMIUM_RATE_ROUTINE : String = "UNAHONCRatingBureauPremiumRateRoutine"
  public static final var NO_PRIOR_INSURANCE_RATE_ROUTINE : String = "UNAHONoPriorInsuranceRateRoutine"
  public static final var TOWNHOUSE_OR_ROWHOUSE_SURCHARGE_RATE_ROUTINE : String = "UNAHOTownhouseOrRowhouseSurchargeRateRoutine"
  public static final var BRUSH_HAZARD_SURCHARGE_RATE_ROUTINE : String = "UNAHOBrushHazardSurchargeRateRoutine"
  public static final var ADJUSTMENT_TO_BCEG_AND_WPDC_CREDIT_RATE_ROUTINE : String = "UNAHOAdjustmentToBCEGAndWPDCCreditRateRoutine"

  public static final var CC_EFT_ACCESSDEVICE_FORGERY_AND_COUNTERFEIT_MONEY : String = "UNAHOCCEFTAccessDeviceForgeryAndCounterfeitMoney"
  public static final var RESIDENCE_HELD_IN_TRUST_RATE_ROUTINE : String = "UNAHOResidenceHeldInTrustRateRoutine"
  public static final var PERSONAL_PROPERTY_OFF_RESIDENCE : String = "UNAPersonalPropertyOffResidence"

  public static final var EQ_LIMITED_COV_CA_RATE_ROUTINE : String = "UNAHOEarthquakeLimitedCovRateRoutine"
  public static final var EQ_COMPREHENSIVE_COV_CA_RATE_ROUTINE :String = "UNAHOEarthquakeComprehensiveCovRateRoutine"
  public static final var EQ_COVERAGE_RATE_ROUTINE_HO3 :String = "UNAHO3EarthquakeCoverageRateRoutine"
  public static final var EQ_COVERAGE_RATE_ROUTINE_HO4 :String = "UNAHO4EarthquakeCoverageRateRoutine"
  public static final var EQ_COVERAGE_RATE_ROUTINE_HO6 :String = "UNAHO6EarthquakeCoverageRateRoutine"
  public static final var UNIT_OWNERS_COVA_INCREASED_LIMIT_RATE_ROUTINE :String = "UNAHOUnitOwnersCovAIncreasedLimitRateRoutine"
  public static final var UNIT_OWNERS_COVA_SPECIAL_LIMITS_RATE_ROUTINE :String = "UNAHOUnitOwnersCovASpecialLimitsRateRoutine"
  public static final var LOSS_HISTORY_CREDIT_RATE_ROUTINE :String = "UNAHOLossHistoryCreditRateRoutine"
  public static final var PROTECTIVE_DEVICE_CREDIT_RATE_ROUTINE :String = "UNAHOProtectiveDeviceCreditRateRoutine"
  public static final var ADDITIONAL_INSURED_PROPERTY_MANAGER_RATE_ROUTINE : String = "UNADPAdditionalInsuredPropertyManagerCovRateRoutine"
  public static final var EQ_COVERAGE_RATE_ROUTINE : String = "UNAHOEarthquakeCoverageRateRoutine"

  //base premium rate routines for DP
  public static final var BASE_PREMIUM_DWELLING_FIRE_RATE_ROUTINE : String = "UNAHODwellingFireBasePremiumRateRoutine"
  public static final var BASE_PREMIUM_DWELLING_FIRE_PERSONAL_PROPERTY_RATE_ROUTINE : String = "UNAHODwellingFirePersonalPropertyRateRoutine"
  public static final var HO_VMM_DWELLING_RATE_ROUTINE : String = "UNAHOVMMDwellingRateRoutine"
  public static final var HO_VMM_CONTENTS_RATE_ROUTINE : String = "UNAHOVMMContentsRateRoutine"
  public static final var HO_EXTENDED_COVERAGE_DWELLING_RATE_ROUTINE : String = "UNAHOExtendedCoverageDwellingRateRoutine"
  public static final var HO_EXTENDED_COVERAGE_CONTENTS_RATE_ROUTINE : String = "UNAHOExtendedCoverageContentsRateRoutine"
  public static final var HO_ADDITIONAL_EXTENDED_COVERAGE_DWELLING_RATE_ROUTINE : String = "UNAHOAdditionalExtendedCoverageDwellingRateRoutine"
  public static final var HO_ADDITIONAL_EXTENDED_COVERAGE_CONTENTS_RATE_ROUTINE : String = "UNAHOAdditionalExtendedCoverageContentsRateRoutine"
  public static final var HO_ALL_RISKS_SPECIAL_COVERAGE_DWELLING_RATE_ROUTINE : String = "UNAHOAllRiskSpecialCoverageDwellingRateRoutine"
  public static final var HO_ALL_RISKS_SPECIAL_COVERAGE_CONTENTS_RATE_ROUTINE : String = "UNAHOAllRiskSpecialCoverageContentsRateRoutine"
  public static final var DP_REPLACEMENT_COST_PERSONAL_PROPERTY_RATE_ROUTINE : String = "UNADPReplacementCostPersonalPropertyRateRoutine"
  public static final var HURRICANE_COV_RATE_ROUTINE : String = "UNAHO3HurricaneCoverageRateRoutine"
  public static final var COMPLETE_HOME_SPRINKLER_SYSTEM_CREDIT_CONTENTS_RATE_ROUTINE : String = "UNAHOCompleteHomeSprinklerSystemContentsRateRoutine"
  public static final var LOSS_FREE_CREDIT_CONTENTS_RATE_ROUTINE : String = "UNAHOLossFreeCreditContentsRateRoutine"
  public static final var COMPLETE_HOME_SPRINKLER_SYSTEM_CREDIT_DWELLING_RATE_ROUTINE : String = "UNAHOCompleteHomeSprinklerSystemDwellingRateRoutine"
  public static final var LOSS_FREE_CREDIT_DWELLING_RATE_ROUTINE : String = "UNAHOLossFreeCreditDwellingRateRoutine"
}