package rules.EventMessage.EventFired_dir.ACCIR010AcceleratorIvansRule_dir


@gw.rules.RuleName("ACCIR011PolicyPeriod")
internal class ACCIR011PolicyPeriod {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.Root typeis PolicyPeriod
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
