package rules.EventMessage.EventFired_dir.LexisFirst_dir

@gw.rules.RuleName("Policy Change")
internal class PolicyChange {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.Root typeis PolicyPeriod
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
