<?xml version="1.0"?>
<definitions targetNamespace="urn:hpexstream-services/Engine" name="EngineService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:hpexstream-services/Engine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:hpexstream-services/Engine" schemaLocation="EngineService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="EngineServiceException">
    <part name="fault" element="tns:EngineServiceException"/>
  </message>
  <message name="Compose">
    <part name="parameters" element="tns:Compose"/>
  </message>
  <message name="ComposeResponse">
    <part name="parameters" element="tns:ComposeResponse"/>
  </message>
  <portType name="EngineWebService">
    <operation name="Compose">
      <input message="tns:Compose"/>
      <output message="tns:ComposeResponse"/>
      <fault name="EngineServiceException" message="tns:EngineServiceException"/>
    </operation>
  </portType>
  <binding name="EngineServicePortBinding" type="tns:EngineWebService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="Compose">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="EngineServiceException">
        <soap:fault name="EngineServiceException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="EngineService">
    <port name="EngineServicePort" binding="tns:EngineServicePortBinding">
      <soap:address location="http://10.1.0.184:9080/EWS/EngineService"/>
    </port>
  </service>
</definitions>