package una.rating.cp.common
/**
 * Created with IntelliJ IDEA.
 * User: bduraiswam007
 */
class CPRateRoutineNames {

  public static final var CP_BUILDING_LOSS_MITIGATION_CREDIT_RATE_ROUTINE : String = "CPBuildingLossMitigationCreditRateRoutine"

  //GroupI rate routine code
  public static final var CP_LIGHTS_GROUPI_RATE_ROUTINE : String = "CPLightstGroupIRateRoutine"
  public static final var CP_FENCE_GROUPI_RATE_ROUTINE : String = "CPFenceGroupIRateRoutine"
  public static final var CP_MAILBOX_GROUPI_RATE_ROUTINE : String = "CPMailBoxGroupIRateRoutine"
  public static final var CP_PLAYGROUND_GROUPI_RATE_ROUTINE : String = "CPPlayGroundGroupIRateRoutine"
  public static final var CP_CARPORT_GROUPI_RATE_ROUTINE : String = "CPCarportGroupIRateRoutine"
  public static final var CP_ENTRY_GATES_GROUPI_RATE_ROUTINE : String = "CPEntryGatesGroupIRateRoutine"
  public static final var CP_FLAGPOLE_GROUPI_RATE_ROUTINE : String = "CPFlagPoleGroupIRateRoutine"
  public static final var CP_POOL_SPA_FOUNTAIN_DECK_GROUPI_RATE_ROUTINE : String = "CPPoolSpaFountainDeckGroupIRateRoutine"
  public static final var CP_SIGNS_DETACHED_OUTDOOR_GROUPI_RATE_ROUTINE : String = "CPSignsDetachedOutdoorGroupIRateRoutine"
  public static final var CP_OTHER_NOC_GROUPI_RATE_ROUTINE : String = "CPOtherNOCGroupIRateRoutine"
  public static final var CP_TRASH_GROUPI_RATE_ROUTINE : String = "CPTrashGroupIRateRoutine"
  public static final var CP_GAZEBO_GROUPI_RATE_ROUTINE : String = "CPGazeboGroupIRateRoutine"
  public static final var CP_SHADE_GROUPI_RATE_ROUTINE : String = "CPShadeGroupIRateRoutine"
  public static final var CP_OUTDOOR_FURNITURE_GROUPI_RATE_ROUTINE : String = "CPOutdoorFurnitureGroupIRateRoutine"
  public static final var CP_BUILDING_COVERAGE_GROUPI_RATE_ROUTINE : String = "CPBuildingCoverageGroupIRateRoutine"
  public static final var CP_PERSONAL_PROPERTY_COVERAGE_GROUPI_RATE_ROUTINE : String = "CPPersonalPropertyCoverageGroupIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_B_GROUPI_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageBGroupIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_C_GROUPI_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageCGroupIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_BC_COMBINED_GROUPI_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageBCCombinedGroupIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_ABC_COMBINED_GROUPI_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageABCCombinedGroupIRateRoutine"
  public static final var CP_TERRORISM_GROUPI_RATE_ROUTINE : String = "CPTerrorismGroupIRateRoutine"

  //GroupII rate routine code
  public static final var CP_EQUIPMENT_BREAKDOWN_ENDORSEMENT_GROUPII_RATE_ROUTINE : String = "CPEquipmentBreakdownEndorsementGroupIIRateRoutine"
  public static final var CP_LIGHTS_GROUPII_RATE_ROUTINE : String = "CPLightstGroupIIRateRoutine"
  public static final var CP_FENCE_GROUPII_RATE_ROUTINE : String = "CPFenceGroupIIRateRoutine"
  public static final var CP_MAILBOX_GROUPII_RATE_ROUTINE : String = "CPMailBoxGroupIIRateRoutine"
  public static final var CP_PLAYGROUND_GROUPII_RATE_ROUTINE : String = "CPPlayGroundGroupIIRateRoutine"
  public static final var CP_CARPORT_GROUPII_RATE_ROUTINE : String = "CPCarportGroupIIRateRoutine"
  public static final var CP_ENTRY_GATES_GROUPII_RATE_ROUTINE : String = "CPEntryGatesGroupIIRateRoutine"
  public static final var CP_FLAGPOLE_GROUPII_RATE_ROUTINE : String = "CPFlagPoleGroupIIRateRoutine"
  public static final var CP_POOL_SPA_FOUNTAIN_DECK_GROUPII_RATE_ROUTINE : String = "CPPoolSpaFountainDeckGroupIIRateRoutine"
  public static final var CP_SIGNS_DETACHED_OUTDOOR_GROUPII_RATE_ROUTINE : String = "CPSignsDetachedOutdoorGroupIIRateRoutine"
  public static final var CP_OTHER_NOC_GROUPII_RATE_ROUTINE : String = "CPOtherNOCGroupIIRateRoutine"
  public static final var CP_TRASH_GROUPII_RATE_ROUTINE : String = "CPTrashGroupIIRateRoutine"
  public static final var CP_GAZEBO_GROUPII_RATE_ROUTINE : String = "CPGazeboGroupIIRateRoutine"
  public static final var CP_SHADE_GROUPII_RATE_ROUTINE : String = "CPShadeGroupIIRateRoutine"
  public static final var CP_OUTDOOR_FURNITURE_GROUPII_RATE_ROUTINE : String = "CPOutdoorFurnitureGroupIIRateRoutine"
  public static final var CP_BUILDING_COVERAGE_GROUPII_RATE_ROUTINE : String = "CPBuildingCoverageGroupIIRateRoutine"
  public static final var CP_PERSONAL_PROPERTY_COVERAGE_GROUPII_RATE_ROUTINE : String = "CPPersonalPropertyCoverageGroupIIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_B_GROUPII_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageBGroupIIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_C_GROUPII_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageCGroupIIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_BC_COMBINED_GROUPII_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageBCCombinedGroupIIRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_ABC_COMBINED_GROUPII_RATE_ROUTINE : String = "CPOrdinanceOrLawCoverageABCCombinedGroupIIRateRoutine"

  //Special cause of loss rate routines
  public static final var CP_BUILDING_COVERAGE_SPECIAL_RATE_ROUTINE : String = "CPBuildingCoverageSpecialRateRoutine"
  public static final var CP_PERSONAL_PROPERTY_COVERAGE_SPECIAL_RATE_ROUTINE : String = "CPPersonalPropertyCoverageSpecialRateRoutine"

  //Windstorm with no hurricane
  public static final var CP_LIGHTS_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPLightsWindstormNoHurricaneRateRoutine"
  public static final var CP_FENCE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPFenceWindstormNoHurricaneRateRoutine"
  public static final var CP_MAILBOX_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPMailBoxWindstormNoHurricaneRateRoutine"
  public static final var CP_PLAYGROUND_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPPlayGroundWindstormNoHurricaneRateRoutine"
  public static final var CP_CARPORT_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPCarportWindstormNoHurricaneRateRoutine"
  public static final var CP_ENTRY_GATES_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPEntryGatesWindstormNoHurricaneRateRoutine"
  public static final var CP_FLAGPOLE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPFlagPoleWindstormNoHurricaneRateRoutine"
  public static final var CP_POOL_SPA_FOUNTAIN_DECK_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPPoolSpaFountainDeckWindstormNoHurricaneRateRoutine"
  public static final var CP_SIGNS_DETACHED_OUTDOOR_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPSignsDetachedOutdoorWindstormNoHurricaneRateRoutine"
  public static final var CP_OTHER_NOC_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOtherNOCWindstormNoHurricaneRateRoutine"
  public static final var CP_TRASH_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPTrashWindstormNoHurricaneRateRoutine"
  public static final var CP_GAZEBO_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPGazeboWindstormNoHurricaneRateRoutine"
  public static final var CP_SHADE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPShadeWindstormNoHurricaneRateRoutine"
  public static final var CP_OUTDOOR_FURNITURE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOutdoorFurnitureWindstormNoHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_B_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovBWindstormNoHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_C_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovCWindstormNoHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_BC_COMBINED_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovBCCombinedWindstormNoHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_ABC_COMBINED_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovABCCombinedWindstormNoHurricaneRateRoutine"
  public static final var CP_BUILDING_COVERAGE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPBuildingCoverageWindstormNoHurricaneRateRoutine"
  public static final var CP_PERSONAL_PROPERTY_COVERAGE_WINDSTORM_NO_HURRICANE_RATE_ROUTINE : String = "CPPersonalPropertyCoverageWindstormNoHurricaneRateRoutine"

  //Windstorm with hurricane
  public static final var CP_LIGHTS_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPLightsWindstormWithHurricaneRateRoutine"
  public static final var CP_FENCE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPFenceWindstormWithHurricaneRateRoutine"
  public static final var CP_MAILBOX_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPMailBoxWindstormWithHurricaneRateRoutine"
  public static final var CP_PLAYGROUND_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPPlayGroundWindstormWithHurricaneRateRoutine"
  public static final var CP_CARPORT_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPCarportWindstormWithHurricaneRateRoutine"
  public static final var CP_ENTRY_GATES_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPEntryGatesWindstormWithHurricaneRateRoutine"
  public static final var CP_FLAGPOLE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPFlagPoleWindstormWithHurricaneRateRoutine"
  public static final var CP_POOL_SPA_FOUNTAIN_DECK_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPPoolSpaFountainDeckWindstormWithHurricaneRateRoutine"
  public static final var CP_SIGNS_DETACHED_OUTDOOR_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPSignsDetachedOutdoorWindstormWithHurricaneRateRoutine"
  public static final var CP_OTHER_NOC_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOtherNOCWindstormWithHurricaneRateRoutine"
  public static final var CP_TRASH_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPTrashWindstormWithHurricaneRateRoutine"
  public static final var CP_GAZEBO_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPGazeboWindstormWithHurricaneRateRoutine"
  public static final var CP_SHADE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPShadeWindstormWithHurricaneRateRoutine"
  public static final var CP_OUTDOOR_FURNITURE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOutdoorFurnitureWindstormWithHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_B_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovBWindstormWithHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_C_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovCWindstormWithHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_BC_COMBINED_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovBCCombinedWindstormWithHurricaneRateRoutine"
  public static final var CP_ORDINANCE_OR_LAW_COVERAGE_ABC_COMBINED_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPOrdOrLawCovABCCombinedWindstormWithHurricaneRateRoutine"
  public static final var CP_BUILDING_COVERAGE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPBuildingCoverageWindstormWithHurricaneRateRoutine"
  public static final var CP_PERSONAL_PROPERTY_COVERAGE_WINDSTORM_WITH_HURRICANE_RATE_ROUTINE : String = "CPPersonalPropertyCoverageWindstormWithHurricaneRateRoutine"

  //Taxes and fees
  public static final var CP_EMPA_SURCHARGE_RATE_ROUTINE : String = "CPEMPASurchargeRateRoutine"
  public static final var CP_POLICY_FEES_RATE_ROUTINE : String = "CPPolicyFeesRateRoutine"
  public static final var CP_FIRE_COLLEGE_SURCHARGE_RATE_ROUTINE : String = "CPFireCollegeSurchargeRateRoutine"
}