package gw.sampledata.forms
uses gw.api.builder.FormPatternBuilder
uses gw.api.builder.FormPatternCovTermBuilder
uses gw.api.builder.FormPatternCovTermValueBuilder
uses gw.api.util.DateUtil
uses gw.transaction.Transaction

@Export
class HOSampleFormData_HOE extends AbstractSampleFormData {

 construct() {
 }

 override property get CollectionName() : String {
   return "HomeownersLine Forms"
 }

 override property get AlreadyLoaded() : boolean {
   return formPatternLoaded("DPDW_DP0106_HOE")
 }

  override function load() {
    Transaction.runWithNewBundle(\ bundle -> {
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0106_HOE")
        .withFormNumber("DP 01 06")
        .withEdition("0100")
        .withDescription("Special Provisions - Alabama")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(720)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0109_HOE")
        .withFormNumber("DP 01 09")
        .withEdition("0100")
        .withDescription("Special Provisions - Florida")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(700)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0172_HOE")
        .withFormNumber("DP 01 72")
        .withEdition("0100")
        .withDescription("Special Provisions - Nevada")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(680)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "NV", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0321_HOE")
        .withFormNumber("DP 03 21")
        .withEdition("0100")
        .withDescription("Windstorm or Hail Percentage Deductible")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(660)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_SectionI_Ded_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("HODW_WindHail_Ded_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("2")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("1")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("5")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0343_HOE")
        .withFormNumber("DP 03 43")
        .withEdition("0100")
        .withDescription("Fungi, Wet or Dry Rot, Bacteria Increased Amount of Section II Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(640)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0387_HOE")
        .withFormNumber("DP 03 87")
        .withEdition("0100")
        .withDescription("Fungi, Wet or Dry Rot, Bacteria Increased Amount of Section I Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(620)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0390_HOE")
        .withFormNumber("DP 03 90")
        .withEdition("0100")
        .withDescription("Windstorm of Hail Exclusion - Alabama")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(600)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0409_HOE")
        .withFormNumber("DP 04 09")
        .withEdition("0100")
        .withDescription("Personal Property Replacement Cost Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(580)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_Personal_Property_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_PropertyValuation_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Replacement")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0416_HOE")
        .withFormNumber("DP 04 16")
        .withEdition("0100")
        .withDescription("Schedule Personal Property")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(560)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0418_HOE")
        .withFormNumber("DP 04 18")
        .withEdition("0100")
        .withDescription("Actual Cash Value Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(520)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_Dwelling_Cov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_ValuationMethod_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("HOActual_HOE")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0427_HOE")
        .withFormNumber("DP 04 27")
        .withEdition("0100")
        .withDescription("Broad Theft Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(800)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_Theft_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_TheftBasis_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Broad")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0437_HOE")
        .withFormNumber("DP 04 37")
        .withEdition("0100")
        .withDescription("Limited Theft Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(500)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_Theft_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_TheftBasis_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Limited")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0445_HOE")
        .withFormNumber("DP 04 45")
        .withEdition("0100")
        .withDescription("Earthquake Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(480)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0464_HOE")
        .withFormNumber("DP 04 64")
        .withEdition("0100")
        .withDescription("Inflation Guard")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(460)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0472_HOE")
        .withFormNumber("DP 04 72")
        .withEdition("0100")
        .withDescription("Limited Fungi, Wet or Dry Rot, Bacteria Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(440)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0477_HOE")
        .withFormNumber("DP 04 77")
        .withEdition("0100")
        .withDescription("Ordinance or Law Increased Amount of Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(420)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_OrdinanceCov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_OrdinanceLimit_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("30")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("25")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("20")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("15")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0498_HOE")
        .withFormNumber("DP 04 98")
        .withEdition("0100")
        .withDescription("Windstorm of Hail Exclusion - Florida")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(400)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0503_HOE")
        .withFormNumber("DP 05 03")
        .withEdition("0100")
        .withDescription("Functional Replacement Cost Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(380)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("DPDW_Dwelling_Cov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("DPDW_ValuationMethod_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("HOReplacement_HOE")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("DPDW_DP0690_HOE")
        .withFormNumber("DP 06 90")
        .withEdition("0100")
        .withDescription("Earthquake Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(360)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Renewal")
        .withJob("Rewrite")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODP_DPForm_HOE")
        .withFormNumber("DP 00 02")
        .withEdition("0100")
        .withDescription("Dwelling Property 2 Broad Form")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(1)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0106_HOE")
        .withFormNumber("HO 01 06")
        .withEdition("0100")
        .withDescription("Special Provisions - Alabama")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(340)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0109_HOE")
        .withFormNumber("HO 01 09")
        .withEdition("0100")
        .withDescription("Special Provisions - Florida")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(320)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0172_HOE")
        .withFormNumber("HO 01 72")
        .withEdition("0100")
        .withDescription("Special Provisions - Nevada")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(300)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "NV", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0310_HOE")
        .withFormNumber("HO 03 10")
        .withEdition("0100")
        .withDescription("Hurricane Percentage Deductible - Alabama")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(280)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0311_HOE")
        .withFormNumber("HO 03 11")
        .withEdition("0100")
        .withDescription("Hurricane Percentage Deductible - Florida")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(265)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0321_HOE")
        .withFormNumber("HO 03 21")
        .withEdition("0100")
        .withDescription("Windstorm or Hail Percentage Deductible")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(240)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0343_HOE")
        .withFormNumber("HO 03 43")
        .withEdition("0100")
        .withDescription("Fungi, Wet or Dry Rot, Bacteria Increased Amount of Section II Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(225)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0366_HOE")
        .withFormNumber("HO 03 66")
        .withEdition("0100")
        .withDescription("Fungi, Wet or Dry Rot, Bacteria Increased Amount of Section I Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(210)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0390_HOE")
        .withFormNumber("HO 03 90")
        .withEdition("0100")
        .withDescription("Windstorm of Hail Exclusion - Alabama")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(195)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "AL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0409_HOE")
        .withFormNumber("HO 04 09")
        .withEdition("0100")
        .withDescription("Personal Property Replacement Cost Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(180)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_Personal_Property_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("HODW_PropertyValuation_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Replacement")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0412_HOE")
        .withFormNumber("HO 04 12")
        .withEdition("0100")
        .withDescription("Windstorm Protective Devices")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(860)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_WindProtectionDevise_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0416_HOE")
        .withFormNumber("HO 04 16")
        .withEdition("0100")
        .withDescription("Schedule Personal Property")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(165)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0418_HOE")
        .withFormNumber("HO 04 18")
        .withEdition("0100")
        .withDescription("Actual Cash Value Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(150)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Renewal")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_Dwelling_Cov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("HODW_DwellingValuation_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Actual")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0428_HOE")
        .withFormNumber("HO 04 28")
        .withEdition("0100")
        .withDescription("Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(880)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_LossSettlement_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0445_HOE")
        .withFormNumber("HO 04 45")
        .withEdition("0100")
        .withDescription("Earthquake Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(135)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0461_HOE")
        .withFormNumber("HO 04 61")
        .withEdition("0100")
        .withDescription("Premises Alarm Or Fire Protection System")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(830)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_AlarmFire_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0464_HOE")
        .withFormNumber("HO 04 64")
        .withEdition("0100")
        .withDescription("Inflation Guard")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(120)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0465_HOE")
        .withFormNumber("HO 04 65")
        .withEdition("0100")
        .withDescription("Special Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(105)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0472_HOE")
        .withFormNumber("HO 04 72")
        .withEdition("0100")
        .withDescription("Limited Fungi, Wet or Dry Rot, Bacteria Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(90)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0477_HOE")
        .withFormNumber("HO 04 77")
        .withEdition("0100")
        .withDescription("Ordinance or Law Increased Amount of Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(75)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_OrdinanceCov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("HODW_OrdinanceLimit_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("30")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("25")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("15")
          )
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("20")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0480_HOE")
        .withFormNumber("HO 04 80")
        .withEdition("0100")
        .withDescription("Other Structures on the Residence Premises – Increased Limits")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(60)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0498_HOE")
        .withFormNumber("HO 04 98")
        .withEdition("0100")
        .withDescription("Windstorm of Hail Exclusion - Florida")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(45)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0503Form_HOE")
        .withFormNumber("HO 05 03")
        .withEdition("0100")
        .withDescription("Functional Replacement Cost Loss Settlement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(30)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Submission")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericCovTermSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_Dwelling_Cov_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .withFormPatternCovTerm(new FormPatternCovTermBuilder()
          .withCovTermPatternCode("HODW_DwellingValuation_HOE")
          .withSelectedCovTermValue(new FormPatternCovTermValueBuilder()
            .withCode("Replacement")
          )
        )
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0561_HOE")
        .withFormNumber("HO 05 61")
        .withEdition("0100")
        .withDescription("Exclusion Of Terrorism (With Limited Exception) And Exclusion Of War")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(900)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Rewrite")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_LimitedTerrorismExc_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0571_HOE")
        .withFormNumber("HO 05 71")
        .withEdition("0100")
        .withDescription("Exclusion Of War And Terrorism")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(910)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_Terrorism_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0690Form_HOE")
        .withFormNumber("HO 06 90")
        .withEdition("0100")
        .withDescription("Earthquake Coverage")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(15)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, "FL", null)
        .withLookup(false, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO0735_HOE")
        .withFormNumber("HO 07 35")
        .withEdition("0100")
        .withDescription("Exclusion - Personal And Advertising Injury")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(920)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_PersonalAdvertisingExc_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO1690_HOE")
        .withFormNumber("HO 16 90")
        .withEdition("0100")
        .withDescription("Water Exclusion Endorsement")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(950)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Renewal")
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericClauseSelectionForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode("HODW_WaterExc_HOE")
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(false)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO3Form_HOE")
        .withFormNumber("HO 00 03")
        .withEdition("0100")
        .withDescription("Homeowners 3 Special Form")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(1)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Submission")
        .withJob("PolicyChange")
        .withJob("Renewal")
        .withJob("Rewrite")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HO6Form_HOE")
        .withFormNumber("HO 00 06")
        .withEdition("0100")
        .withDescription("Homeowners Units Owner Form")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(1)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("Rewrite")
        .withJob("Submission")
        .withJob("Renewal")
        .withJob("PolicyChange")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
 
      new FormPatternBuilder()
        // Basics
        .withCode("HODW_HOForm_HOE")
        .withFormNumber("HO 00 04")
        .withEdition("0100")
        .withDescription("Homeowners 4 Contents Broad Form")
        .withInferenceTime("quote")
        .withEndorsementNumbered(false)
        .withPriority(1)
        .withRefCode(null)
        // Products
        .withProduct("Homeowners")
        // Jobs
        .withJob("PolicyChange")
        .withJob("Submission")
        .withJob("Rewrite")
        .withJob("Renewal")
        // Jurisdictions
        .withLookup(true, DateUtil.createDateInstance(1, 1, 2000), null, null, null)
        .withInternalGroupCode(null)
        .withUseInsteadOfCode(null)
        // Policy Change
        .withInternalRemovalEndorsement(false)
        .withInternalReissueOnChange(true)
        .withRemovalEndorsementFormNumber(null)
        // Inference
        .withGenericInferenceClass("gw.forms.generic.GenericAlwaysAddedForm")
        .withPolicyLinePatternCode("HomeownersLine_HOE")
        .withClausePatternCode(null)
        .withPatternExistsOnAll(false)
        .withCoverableType(null as String)
        .withCoverableTypeList(null as String)
        .withCoverableTypeKey(null as String)
        .withCoverableTypeKeyExistsOnAll(null)
        .create(bundle)
    })
  }
}
 
