package rules.EventMessage.EventFired_dir


@gw.rules.RuleName("ACCIR010AcceleratorIvansRule")
internal class ACCIR010AcceleratorIvansRule {
  static function doCondition(messageContext     :     entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.DestID == 23
/*end00rule*/
}

  static function doAction(messageContext     :     entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
