package rules.EventMessage.EventFired_dir
uses una.integration.plugins.ivans.IvansOutboundMessageTransportPluginImpl

@gw.rules.RuleName("IVANS")
internal class IVANS {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.DestID==IvansOutboundMessageTransportPluginImpl.DEST_ID
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
