package rules.EventMessage.EventFired_dir
uses una.integration.plugins.lexisfirst.LexisFirstOutboundPluginImpl

@gw.rules.RuleName("LexisFirst")
internal class LexisFirst {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.DestID == LexisFirstOutboundPluginImpl.DEST_ID
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
